/**
 * Semantic icon map for Lash Designer.
 *
 * Screens import product meanings from this file while the glyphs come from
 * Phosphor Icons. Per-icon CSR entry points keep the development server and
 * production bundle from eagerly loading the entire icon catalogue.
 */
export { SquaresFourIcon as LayoutDashboard } from '@phosphor-icons/react/dist/csr/SquaresFour'
export { CalendarBlankIcon as Calendar } from '@phosphor-icons/react/dist/csr/CalendarBlank'
export { CalendarDotsIcon as CalendarDays, CalendarDotsIcon as CalendarDots } from '@phosphor-icons/react/dist/csr/CalendarDots'
export { ClipboardTextIcon as ClipboardList } from '@phosphor-icons/react/dist/csr/ClipboardText'
export { UsersThreeIcon as Users, UsersThreeIcon as UsersRound } from '@phosphor-icons/react/dist/csr/UsersThree'
export { WalletIcon as Wallet, WalletIcon as WalletCards } from '@phosphor-icons/react/dist/csr/Wallet'
export { GearSixIcon as Settings } from '@phosphor-icons/react/dist/csr/GearSix'
export { ChatCenteredTextIcon as MessageSquare } from '@phosphor-icons/react/dist/csr/ChatCenteredText'
export { ChatCircleDotsIcon as MessageCircleMore } from '@phosphor-icons/react/dist/csr/ChatCircleDots'
export { SignOutIcon as LogOut } from '@phosphor-icons/react/dist/csr/SignOut'
export { ListIcon as Menu } from '@phosphor-icons/react/dist/csr/List'
export { SidebarSimpleIcon as SidebarSimple } from '@phosphor-icons/react/dist/csr/SidebarSimple'
export { MagnifyingGlassIcon as Search } from '@phosphor-icons/react/dist/csr/MagnifyingGlass'
export { PlusIcon as Plus } from '@phosphor-icons/react/dist/csr/Plus'
export { CheckIcon as Check } from '@phosphor-icons/react/dist/csr/Check'
export { XIcon as X } from '@phosphor-icons/react/dist/csr/X'
export { XCircleIcon as XCircle } from '@phosphor-icons/react/dist/csr/XCircle'
export { CheckCircleIcon as CheckCircle2 } from '@phosphor-icons/react/dist/csr/CheckCircle'
export { WarningCircleIcon as AlertCircle } from '@phosphor-icons/react/dist/csr/WarningCircle'
export { InfoIcon as Info } from '@phosphor-icons/react/dist/csr/Info'
export { WarningIcon as AlertTriangle } from '@phosphor-icons/react/dist/csr/Warning'
export { ClockIcon as Clock, ClockIcon as Clock3 } from '@phosphor-icons/react/dist/csr/Clock'
export { CaretLeftIcon as ChevronLeft } from '@phosphor-icons/react/dist/csr/CaretLeft'
export { CaretRightIcon as ChevronRight } from '@phosphor-icons/react/dist/csr/CaretRight'
export { CaretDownIcon as ChevronDown } from '@phosphor-icons/react/dist/csr/CaretDown'
export { ArrowRightIcon as ArrowRight } from '@phosphor-icons/react/dist/csr/ArrowRight'
export { PaperPlaneTiltIcon as Send } from '@phosphor-icons/react/dist/csr/PaperPlaneTilt'
export { StopCircleIcon as StopCircle } from '@phosphor-icons/react/dist/csr/StopCircle'
export { DotsThreeIcon as MoreHorizontal } from '@phosphor-icons/react/dist/csr/DotsThree'
export { PencilSimpleIcon as Edit2 } from '@phosphor-icons/react/dist/csr/PencilSimple'
export { ImageIcon, ImageIcon as Image } from '@phosphor-icons/react/dist/csr/Image'
export { LinkIcon as Link2 } from '@phosphor-icons/react/dist/csr/Link'
export { UploadSimpleIcon as Upload } from '@phosphor-icons/react/dist/csr/UploadSimple'
export { DownloadSimpleIcon as Download } from '@phosphor-icons/react/dist/csr/DownloadSimple'
export { TrashIcon as Trash2 } from '@phosphor-icons/react/dist/csr/Trash'
export { ShieldCheckIcon as ShieldCheck } from '@phosphor-icons/react/dist/csr/ShieldCheck'
export { LockKeyIcon as Lock, LockKeyIcon as LockKeyhole } from '@phosphor-icons/react/dist/csr/LockKey'
export { EyeIcon as Eye } from '@phosphor-icons/react/dist/csr/Eye'
export { EyeSlashIcon as EyeOff } from '@phosphor-icons/react/dist/csr/EyeSlash'
export { BellIcon as Bell } from '@phosphor-icons/react/dist/csr/Bell'
export { BellRingingIcon as BellRing } from '@phosphor-icons/react/dist/csr/BellRinging'
export { CopyIcon as Copy } from '@phosphor-icons/react/dist/csr/Copy'
export { DeviceMobileIcon as Smartphone } from '@phosphor-icons/react/dist/csr/DeviceMobile'
export { GlobeHemisphereWestIcon as Globe, GlobeHemisphereWestIcon as Globe2 } from '@phosphor-icons/react/dist/csr/GlobeHemisphereWest'
export { CreditCardIcon as CreditCard } from '@phosphor-icons/react/dist/csr/CreditCard'
export { DatabaseIcon as Database } from '@phosphor-icons/react/dist/csr/Database'
export { PlugsConnectedIcon as Webhook } from '@phosphor-icons/react/dist/csr/PlugsConnected'
export { MegaphoneIcon as Megaphone } from '@phosphor-icons/react/dist/csr/Megaphone'
export { QrCodeIcon as QrCode } from '@phosphor-icons/react/dist/csr/QrCode'
export { MoonIcon as Moon } from '@phosphor-icons/react/dist/csr/Moon'
export { SunIcon as Sun } from '@phosphor-icons/react/dist/csr/Sun'
export { PaletteIcon as Palette } from '@phosphor-icons/react/dist/csr/Palette'
export { QuestionIcon as CircleHelp } from '@phosphor-icons/react/dist/csr/Question'
export { CompassIcon as Compass } from '@phosphor-icons/react/dist/csr/Compass'
export { SparkleIcon as Sparkles } from '@phosphor-icons/react/dist/csr/Sparkle'
export { StarIcon as Star } from '@phosphor-icons/react/dist/csr/Star'
export { ChartBarIcon as BarChart3 } from '@phosphor-icons/react/dist/csr/ChartBar'
export { LightningIcon as Zap } from '@phosphor-icons/react/dist/csr/Lightning'
export { HandHeartIcon as HeartHandshake } from '@phosphor-icons/react/dist/csr/HandHeart'
export { PlayCircleIcon as PlayCircle } from '@phosphor-icons/react/dist/csr/PlayCircle'
export { ArrowClockwiseIcon as RefreshCw } from '@phosphor-icons/react/dist/csr/ArrowClockwise'
export { ArrowSquareOutIcon as ExternalLink } from '@phosphor-icons/react/dist/csr/ArrowSquareOut'

export { PaperclipIcon as Paperclip } from '@phosphor-icons/react/dist/csr/Paperclip'
