from pathlib import Path
from playwright.sync_api import sync_playwright
import json
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'visual-output-mobile510-part2'; OUT.mkdir(exist_ok=True)
css='\n'.join((ROOT/'src'/f).read_text() for f in ['styles.css','design-system.css','product-system-v33.css','product-controls-v40.css','foundation-v24.css','forms-v24.css','services-v24.css','whatsapp-v39.css','mobile-app-v510.css'])
base=f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>{css}\n*{{box-sizing:border-box}} body{{margin:0;background:var(--surface-canvas);font-family:var(--font-ui);color:var(--ink-strong)}} .qa{{padding:12px 12px 90px}}</style></head><body><main class="qa" id="root"></main></body></html>'''
clients='''<div class="card client-admin-page"><div class="cardHeader client-admin-header"><div><h2 class="cardTitle">Clientes</h2><p>Base de clientes do seu espaço.</p></div><span class="client-count-badge">18</span></div><label class="client-search"><span>⌕</span><input placeholder="Buscar por nome, telefone ou e-mail"><button>×</button></label><div class="client-mobile-list"><article class="client-mobile-card"><div class="user-avatar-mini client-mobile-avatar">MS</div><div class="client-mobile-main"><strong>Mariana Souza</strong><span>(35) 99916-7985</span><div class="client-mobile-tags"><em class="is-ok">Promoções autorizadas</em><em>Última visita 12/08/2026</em></div></div><div class="client-mobile-value"><small>Total</small><strong>R$ 840,00</strong></div></article><article class="client-mobile-card"><div class="user-avatar-mini client-mobile-avatar">AC</div><div class="client-mobile-main"><strong>Ana Carolina</strong><span>ana@email.com</span><div class="client-mobile-tags"><em>Sem promoções</em><em>Primeira visita pendente</em></div></div><div class="client-mobile-value"><small>Total</small><strong>R$ 190,00</strong></div></article></div></div>'''
services='''<div class="card service-admin-page"><div class="cardHeader service-admin-header"><div><h2 class="cardTitle">Serviços</h2><p>Gerencie os serviços oferecidos.</p></div><button class="btn btnPrimary service-create-button">＋ Novo serviço</button></div><div class="service-mobile-list"><article class="service-mobile-card"><img src="/placeholders/service-placeholder.webp"><div class="service-mobile-copy"><strong>Extensão clássica</strong><div class="service-mobile-meta"><span>120 min</span><b>R$ 150,00</b></div></div><button class="icon-btn service-mobile-edit">✎</button></article><article class="service-mobile-card"><img src="/placeholders/service-placeholder.webp"><div class="service-mobile-copy"><strong>Volume brasileiro</strong><div class="service-mobile-meta"><span>150 min</span><b>R$ 190,00</b></div></div><button class="icon-btn service-mobile-edit">✎</button></article><article class="service-mobile-card"><img src="/placeholders/service-placeholder.webp"><div class="service-mobile-copy"><strong>Manutenção</strong><div class="service-mobile-meta"><span>90 min</span><b>R$ 100,00</b></div></div><button class="icon-btn service-mobile-edit">✎</button></article></div></div>'''
whatsapp='''<div class="wa39"><header class="wa39-topbar"><div><span class="wa39-eyebrow">Central de relacionamento</span><h2>WhatsApp</h2><p>Conversas e confirmações.</p></div><div class="wa39-health is-connected"><i></i><span>Conectado</span></div></header><nav class="wa39-tabs"><button class="is-active"><span>▢</span><span>Conversas</span><b>2</b></button><button><span>◌</span><span>Automações</span></button><button><span>◇</span><span>Campanhas</span></button><button><span>⚙</span><span>Conexão</span></button></nav><section class="wa39-inbox"><aside class="wa39-conversation-pane"><div class="wa39-pane-head"><div><strong>Conversas</strong><small>2 contatos</small></div><button class="wa39-icon-button">＋</button></div><label class="wa39-search"><span>⌕</span><input placeholder="Buscar nome ou número"></label><div class="wa39-conversation-list"><button class="wa39-conversation is-active"><span class="wa39-avatar">MS</span><span class="wa39-conversation-copy"><span class="wa39-conversation-line"><strong>Mariana Souza</strong><time>agora</time></span><span class="wa39-conversation-phone">(35) 99916-7985</span><span class="wa39-conversation-line is-preview"><span>Você: Te espero amanhã às 14h.</span><b>2</b></span></span></button><button class="wa39-conversation"><span class="wa39-avatar">AC</span><span class="wa39-conversation-copy"><span class="wa39-conversation-line"><strong>Ana Carolina</strong><time>12 min</time></span><span class="wa39-conversation-phone">(35) 98888-7788</span><span class="wa39-conversation-line is-preview"><span>Oi, queria saber os horários.</span></span></span></button></div></aside></section></div>'''
whatsapp_chat='''<div class="wa39"><header class="wa39-topbar"><div><span class="wa39-eyebrow">Central</span><h2>WhatsApp</h2></div><div class="wa39-health is-connected"><i></i><span>Conectado</span></div></header><nav class="wa39-tabs"><button class="is-active"><span>▢</span><span>Conversas</span><b>2</b></button><button><span>◌</span><span>Automações</span></button><button><span>◇</span><span>Campanhas</span></button><button><span>⚙</span><span>Conexão</span></button></nav><section class="wa39-inbox is-mobile-chat-open"><aside class="wa39-conversation-pane"></aside><main class="wa39-chat-pane"><header class="wa39-chat-head"><button class="wa39-chat-back">‹</button><div class="wa39-chat-person"><span class="wa39-avatar is-large">MS</span><div><strong>Mariana Souza</strong><span>(35) 99916-7985</span></div></div><button class="wa39-luma-reply">✦<span>Sugerir resposta</span></button></header><div class="wa39-messages"><article class="wa39-message is-inbound"><p>Oi! Você tem horário amanhã à tarde?</p><footer><time>13:18</time></footer></article><article class="wa39-message is-outbound"><p>Tenho sim. Posso te atender às 14h ou 16h.</p><footer><time>13:19</time></footer></article><article class="wa39-message is-inbound"><p>14h fica perfeito 😊</p><footer><time>13:20</time></footer></article></div><form class="wa39-composer"><button class="wa39-composer-tool">＋</button><textarea placeholder="Escreva uma mensagem…"></textarea><button class="wa39-send">➤</button></form></main></section></div>'''
screens={'clients':clients,'services':services,'whatsapp':whatsapp,'whatsapp-chat':whatsapp_chat}
results=[]
with sync_playwright() as p:
  b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage'])
  for name,markup in screens.items():
    for w,h in [(390,844),(430,900),(768,900)]:
      pg=b.new_page(viewport={'width':w,'height':h})
      pg.set_content(base,wait_until='domcontentloaded')
      pg.locator('#root').evaluate('(el, html) => el.innerHTML=html',markup)
      pg.wait_for_timeout(50)
      metrics=pg.evaluate('''() => ({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth, body:document.body.scrollWidth})''')
      fail=metrics['sw']>metrics['cw']+2
      fn=f'{name}-{w}.png'; pg.screenshot(path=str(OUT/fn),full_page=False)
      results.append({'screen':name,'viewport':w,'fail':fail,**metrics,'shot':fn})
      pg.close()
  b.close()
(OUT/'matrix.json').write_text(json.dumps(results,indent=2,ensure_ascii=False))
print(json.dumps({'cases':len(results),'failures':sum(r['fail'] for r in results)},indent=2))
