import fs from 'node:fs'
import path from 'node:path'
const root=process.cwd(); const read=(f)=>fs.readFileSync(path.join(root,f),'utf8')
const files=[]; const walk=(d)=>{for(const e of fs.readdirSync(path.join(root,d),{withFileTypes:true})){const r=path.join(d,e.name);if(e.isDirectory())walk(r);else if(/\.tsx?$/.test(e.name))files.push(r)}}; walk('src')
const source=files.map(read).join('\n'), app=read('src/App.tsx'), tour=read('src/components/ProductTour.tsx'), coordinator=read('src/components/OverlayCoordinator.tsx'), modalRoot=read('src/components/ModalRoot.tsx'), overlayCss=read('src/overlays-v24.css'), shellCss=read('src/shell-v24.css'), landing=read('src/LandingPage.tsx'), setup=read('src/components/WorkspaceSetup.tsx'), pkg=JSON.parse(read('package.json'))
const checks=[]; const assert=(ok,label)=>checks.push({ok:Boolean(ok),label})
const modalRoots=(source.match(/<ModalRoot\b/g)||[]).length
assert(modalRoots>=8, `auditoria encontrou ${modalRoots} superfícies usando ModalRoot`)
assert(modalRoot.includes('createPortal') && modalRoot.includes('document.body'), 'ModalRoot monta diretamente no body')
assert(coordinator.includes('MutationObserver') && coordinator.includes('focusableSelector'), 'coordenador global controla foco e mudanças de overlay')
assert(coordinator.includes("querySelector<HTMLElement>('[autofocus]')") && setup.includes('autoFocus className'), 'overlays priorizam foco inicial explícito')
assert(coordinator.includes('overlay === activeOverlay') && coordinator.includes('returnFocus?.isConnected'), 'coordenador acompanha overlays empilhados e restaura foco')
assert(coordinator.includes("event.key === 'Escape'") && coordinator.includes("event.key !== 'Tab'"), 'modais suportam Escape e contenção de Tab')
assert(coordinator.includes("classList.add('has-blocking-overlay')") && tour.includes("classList.add('has-product-tour')"), 'scroll lock de modal e tour usa flags independentes')
assert(overlayCss.includes('.ld-overlay') && overlayCss.includes('z-index: 1000') && read('src/tour-v24.css').includes('z-index:900'), 'overlays transacionais têm prioridade visual consistente')
assert(!tour.includes("document.body.style.overflow = 'hidden'") && !coordinator.includes("document.body.style.overflow = 'hidden'"), 'componentes não manipulam overflow inline')
assert(tour.includes('hasBlockingOverlay') && tour.includes('lashdesigner:overlay-open'), 'Product Tour encerra quando overlay bloqueante aparece')
assert(tour.includes("['v3', 'v2', 'v1']") || tour.includes('v3'), 'Product Tour mantém versão persistente de conclusão')
assert(app.includes("tourEnabled={!subscriptionInactive && tab !== 'billing'}") && app.includes("if (subscriptionInactive && tab !== 'billing') setTab('billing')"), 'billing e Product Tour obedecem ao estado da assinatura')
assert(!source.includes('wa.me/') && landing.includes('<LandingCheckout') && landing.includes("onClick={() => buy("), 'CTA comercial inicia checkout direto')
assert(setup.includes("'ASSISTED' | 'MANUAL'") && setup.includes('/api/admin/onboarding/complete'), 'setup possui caminhos assistido e manual')
assert(app.includes("localStorage.getItem('lashdesigner:sidebar-collapsed')") && app.includes("localStorage.setItem('lashdesigner:sidebar-collapsed'"), 'sidebar recolhível persiste preferência')
assert(shellCss.includes('.ld-sidebar.is-open') && shellCss.includes('.ld-mobile-backdrop'), 'drawer mobile possui estado próprio')
assert(app.includes("weight: props.active ? 'duotone' : 'regular'"), 'estado ativo usa hierarquia Phosphor consistente')
assert(pkg.scripts['test:ux']==='node scripts/ux-audit.mjs','auditoria UX permanece no pipeline')
const failed=checks.filter(c=>!c.ok); for(const c of checks)console.log(`${c.ok?'✓':'✗'} ${c.label}`); console.log(`\n${checks.length-failed.length}/${checks.length} verificações UX aprovadas.`); if(failed.length)process.exit(1)
